/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
    ],
    safelist: [  // ← добавь этот блок
        'bg-red-500',
        'bg-green-600',
        'bg-blue-600',
        'bg-indigo-600',
        'bg-purple-600',
        'bg-yellow-500',
        'bg-red-700',
        'bg-green-700',
        'bg-blue-700',
        'bg-indigo-700',
        'bg-purple-700',
        'bg-gray-400',
        'bg-gray-500',
        'bg-gray-600',
        'text-white',
        'text-gray-800',
        'text-gray-600',
        'text-red-600',
        'hover:bg-red-700',
        'hover:bg-green-700',
        'hover:bg-blue-700',
        'hover:bg-indigo-700',
        'hover:bg-purple-700',
        'hover:bg-yellow-600',
        'hover:scale-105',
        'transition-all',
        'duration-300',
        'rounded-lg',
        'rounded-xl',
        'rounded-2xl',
        'shadow-lg',
        'shadow-md',
        'shadow-2xl',
        'border',
        'border-gray-100',
        'p-6',
        'p-8',
        'p-10',
        'py-3',
        'py-4',
        'px-8',
        'px-10',
        'flex',
        'justify-center',
        'gap-4',
        'gap-6',
        'gap-8',
        'space-y-2',
        'space-y-6',
        'font-bold',
        'font-medium',
        'text-2xl',
        'text-3xl',
        'text-4xl',
        'text-lg',
        'disabled:opacity-50',
    ],
    theme: {
        extend: {},
    },
    plugins: [],
}